# Generated by Django 5.1.6 on 2025-03-21 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0002_memberrelation_created_id_alter_memberrelation_no_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberrelation',
            old_name='created_id',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='memberrelation',
            old_name='no_id',
            new_name='record',
        ),
    ]
