# Generated by Django 5.1.6 on 2025-03-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0003_rename_created_id_memberrelation_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(),
        ),
    ]
