# Generated by Django 5.1.6 on 2025-03-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
