# Generated by Django 5.1.6 on 2025-02-22 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='請以 E.164 格式輸入手機號碼，例如 +886912345678', regex='^\\+\\d{10,15}$')]),
        ),
    ]
